# Generated by Django 6.0.1 on 2026-01-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('welkom_titel', models.CharField(default='Welkom bij shantykoor Krakend Tuig', max_length=200)),
                ('welkom_tekst', models.TextField(blank=True)),
                ('mededelingen_titel', models.CharField(default='Mededelingen', max_length=200)),
                ('mededelingen_tekst', models.TextField(blank=True)),
                ('sponsor_titel', models.CharField(default='Ontmoet onze sponsoren', max_length=200)),
                ('sponsor_tekst', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/slides/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('interval_ms', models.PositiveIntegerField(default=5000)),
                ('volgorde', models.PositiveIntegerField(default=0)),
                ('actief', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='website.homepagecontent')),
            ],
            options={
                'ordering': ['volgorde', 'id'],
            },
        ),
    ]
