# Generated by Django 6.0.1 on 2026-01-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='sponsor_tekst',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='sponsor_titel',
        ),
    ]
