# Generated by Django 6.0.1 on 2026-01-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_homepagecontent_sponsor_tekst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='mededelingen_email',
            field=models.EmailField(blank=True, help_text='Wordt als klikbare e-mail weergegeven', max_length=254),
        ),
    ]
