# Generated by Django 6.0.1 on 2026-01-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepagecontent_mededelingen_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZingMeeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://www.youtube.com/embed/l6UBUZQzRHQ')),
                ('video_caption', models.CharField(default='Impressie van een oefenavond uit 2023', max_length=200)),
                ('repetities_regel_1', models.CharField(default='Iedere maandagavond', max_length=100)),
                ('repetities_regel_2', models.CharField(default='19:30 – 21:30', max_length=100)),
                ('repetities_toelichting', models.CharField(blank=True, default='(behalve de eerste maandag van de maand)', max_length=150)),
                ('locatie_regel_1', models.CharField(default='Parochiehuis', max_length=100)),
                ('locatie_regel_2', models.CharField(default='Herenstraat 15', max_length=100)),
                ('locatie_regel_3', models.CharField(default='3621 AP Breukelen', max_length=100)),
                ('contact_kop', models.CharField(default='Interesse?', max_length=50)),
                ('contact_naam', models.CharField(default='Gert Frankhuisen', max_length=100)),
                ('contact_telefoon', models.CharField(default='0625011812', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
