# Generated by Django 6.0.1 on 2026-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optreden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('titel', models.CharField(max_length=200)),
                ('tijd', models.CharField(blank=True, max_length=50)),
                ('locatie', models.CharField(blank=True, max_length=200)),
                ('openbaar', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['datum'],
            },
        ),
    ]
