# Generated by Django 6.0.1 on 2026-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretariaat_titel', models.CharField(default='Adres secretariaat', max_length=200)),
                ('secretariaat_regel1', models.CharField(blank=True, default='Shantykoor Krakend Tuig', max_length=200)),
                ('secretariaat_regel2', models.CharField(blank=True, max_length=200)),
                ('secretariaat_regel3', models.CharField(blank=True, max_length=200)),
                ('secretariaat_email', models.EmailField(blank=True, max_length=254)),
                ('boeken_titel', models.CharField(default='Optreden boeken', max_length=200)),
                ('boeken_naam', models.CharField(blank=True, max_length=200)),
                ('boeken_tel', models.CharField(blank=True, help_text='Bijv. 0625011812', max_length=50)),
                ('boeken_email', models.EmailField(blank=True, max_length=254)),
                ('site_titel', models.CharField(default='Vragen of opmerkingen over de site', max_length=200)),
                ('site_naam', models.CharField(blank=True, max_length=200)),
                ('site_rol', models.CharField(blank=True, default='Webbeheerder', max_length=200)),
                ('site_url', models.URLField(blank=True)),
                ('site_url_label', models.CharField(blank=True, default='Hello Daphne', max_length=200)),
                ('site_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
