# Generated by Django 6.0.1 on 2026-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpagecontent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
    ]
