# Generated by Django 6.0.1 on 2026-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_embed',
            field=models.BooleanField(default=True, help_text='Vink uit als embed niet werkt; dan tonen we een linkknop'),
        ),
    ]
