# Generated by Django 6.0.1 on 2026-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0002_video_is_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, help_text='Upload een MP4-bestand (optioneel)', upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link (optioneel)'),
        ),
    ]
