# Generated by Django 6.0.1 on 2026-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Plaats'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefoon'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode'),
        ),
    ]
