# Generated by Django 6.0.1 on 2026-01-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile_address_memberprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='last_name_prefix',
            field=models.CharField(blank=True, help_text='Bijv. van, van der, de, ten', max_length=30, verbose_name='Tussenvoegsel'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Achternaam'),
        ),
    ]
