# Generated by Django 6.0.1 on 2026-01-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberprofile_last_name_prefix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ['last_name', 'last_name_prefix', 'first_name']},
        ),
    ]
