# Generated by Django 6.0.1 on 2026-01-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_memberprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ['user__last_name', 'user__first_name', 'last_name_prefix']},
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='last_name',
        ),
    ]
