# Generated by Django 6.0.1 on 2026-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_memberprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Gebruiker moet bij volgende login wachtwoord wijzigen'),
        ),
    ]
