# Generated by Django 6.0.1 on 2026-01-29 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Optreden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('datum', models.DateField()),
                ('tijd', models.TimeField(blank=True, null=True)),
                ('locatie', models.CharField(blank=True, max_length=255)),
                ('adres', models.TextField(blank=True)),
                ('actief', models.BooleanField(default=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['datum', 'tijd', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='Aanwezigheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aanwezig', 'Aanwezig'), ('afwezig', 'Afwezig'), ('onzeker', 'Nog niet zeker')], default='onzeker', max_length=10)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aanwezigheden', to=settings.AUTH_USER_MODEL)),
                ('optreden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aanwezigheden', to='planning.optreden')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('optreden', 'user'), name='unique_aanwezigheid_per_optreden_per_user')],
            },
        ),
    ]
