# Generated by Django 6.0.1 on 2026-01-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optreden',
            options={},
        ),
        migrations.RemoveField(
            model_name='optreden',
            name='aangemaakt_op',
        ),
        migrations.AlterField(
            model_name='aanwezigheid',
            name='optreden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.optreden'),
        ),
        migrations.AlterField(
            model_name='aanwezigheid',
            name='status',
            field=models.CharField(blank=True, choices=[('aanwezig', 'Aanwezig'), ('afwezig', 'Afwezig'), ('onzeker', 'Nog niet zeker')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aanwezigheid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
