# Generated by Django 6.0.1 on 2026-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_optreden_options_remove_optreden_aangemaakt_op_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optreden',
            name='openbaar',
            field=models.BooleanField(default=False),
        ),
    ]
