# Generated by Django 6.0.1 on 2026-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_optreden_openbaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optreden',
            name='openbaar',
            field=models.BooleanField(default=True),
        ),
    ]
