# Generated by Django 6.0.1 on 2026-01-26 19:21

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='“Krakend Tuig” – shanty zoals het altijd was', max_length=200)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('paragraph_7', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.about_upload_to)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
