# Generated by Django 6.0.1 on 2026-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.PositiveIntegerField()),
                ('titel', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='liedteksten/')),
                ('actief', models.BooleanField(default=True)),
                ('volgorde', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['volgorde', 'nummer'],
            },
        ),
    ]
